; pytest配置 必須要[pytest] --html=report/测试报告2.html --self-contained-html

; pip install allure-pytest

; 安装https://github.com/allure-framework/allure2/releases 添加bin

; python -m pytest --alluredir=./reports

; allure serve ./reports
[pytest]
addopts = -s 
; python_files = test_* 
python_files = test_index.py 
python_classes = Test*
python_functions = test_*
testpaths = ./script/